openapi: 3.0.3
info:
  title: Guardian live GitHub test
  version: 1.1.1
paths:
  /pets:
    get:
      operationId: listPets
      responses:
        "200":
          description: Pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
  /pets/{petId}:
    get:
      operationId: getPet
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Pet
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
        name:
          type: string
        avatarUrl:
          type: string
          format: uri
